name: animal_conservation
description: An app for photographing and documenting animal sightings.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  firebase_core: ^3.13.0
  camera: ^0.10.5+9
  path: ^1.8.3
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  provider: ^6.1.1
  flutter_file_dialog: ^3.0.0
  http: ^1.1.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^13.0.4
#  geolocator_android: ^5.0.1
  flutter_markdown_plus: ^1.0.3
  flutter_svg_provider: ^1.0.7
  image: ^4.5.4
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  cloud_firestore: ^5.6.6

flutter:
  uses-material-design: true

  # Add assets if needed
  assets:
    - assets/pigeon.webp
    - assets/fox.webp
    - assets/whale.jpg
    - assets/images/default_profile.png
    - assets/images/star_pattern.svg
    - assets/images/star_pattern.png
    - assets/images/dot.png
    - assets/Marker.png
    - assets/images/placeholder_animal.png
    - assets/images/Logo.png
